---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
implicit:
- Сайт должен иметь локализацию на русском и английском языках
- У пользователя должна быть возможность указывать желаемый диапазон цены
- Пользователь может удалить товар из корзины
- Пользователь может изменять количество товаров в корзине
- В мобильной версии сайт трансформируется в удобное меню с возможностью листать каталог и переходить на другие страницы
- При смене языка интерфейс сайта и описание товаров меняется в соответствие с выбранным языком
- Пользователь должен иметь возможность регистрации и авторизации на сайте
- История заказов сохраняется у пользователя в личном кабинете 
- При наличие нескольких товаров в корзине пользователь видит общую стоимость всего заказа
- Цена товара не меняется при добавлении в корзину
- Если товара нет в наличие пользователь увидит соответствующее уведомление 
- Пользователь должен подтверждать добавление заказа в корзину во всплывающем окне
- Пользователь должен подтверждать оформление заказа во всплывающем окне
- Заказ может совершить только авторизованный пользователь
- При оформлении заказа пользователь обязан указывать номер телефона для обратной связи
- При оформлении заказа пользователь может выбрать способ оплаты (картой, картой при получении, наличными)
- Пользователь не может оформить заказ с пустой корзиной
- При выборе категории отображаются товары только выбранной категории
- Если все товары не вмещаются на одной странице пользователь может перейти на следующую
