---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
implicit:
- У пользователя должна быть возможность указывать желаемый диапазон цены
- Пользователь может удалить товар из корзины
- Пользователь может изменять количество товаров в корзине
- В мобильной версии сайт трансформируется в удобное меню с возможностью листать каталог и переходить на другие страницы
- Пользователь должен иметь возможность регистрации и авторизации на сайте
- История заказов сохраняется у пользователя в личном кабинете 
- При наличие нескольких товаров в корзине пользователь видит общую стоимость всего заказа
- Цена товара не меняется при добавлении в корзину
- Пользователь может зарегистрироваться или авторизоваться на сайте
- Если товара нет в наличие пользователь увидит соответствующее уведомление 
- Пользователь должен подтверждать добавление заказа в корзину во всплывающем окне
- Пользователь должен подтверждать оформление заказа во всплывающем окне
- Пользователь видит рейтинг каждого товара
- Пользователь может фильтровать товары по рейтингу
- При оформлении заказа пользователь переходит на страницу оплаты
- При оформлении заказа пользователь может выбрать способ оплаты
- Пользователь не может оформить заказ с пустой корзиной
- При выборе категории отображаются товары только выбранной категории
- Если все товары не вмещаются на одной странице пользователь может перейти на следующую
- При отсутствии соединения с интернетом пользователь видит соответствующую плашку
- В каталоге выводится цена со скидкой и без скидки для каждого товара
- В каталоге выводится название для каждого товара
- В каталоге выводится рейтинг каждого товара
- В карточке каждого товара выводится цена со скидкой и без скидки, название, описание товара, рейтинг товара
